Gracefully handle pull requests without bodies
Calling `repo_and_version_of_pull_request_body` with an empty body
causes errors due to `occursin` not handling `Nothing` values.

```julia
ERROR: MethodError: no method matching occursin(::String, ::Nothing)
Closest candidates are:
  occursin(::Union{AbstractChar, AbstractString}, ::AbstractString) at strings/search.jl:628
  occursin(::Any) at strings/search.jl:642
Stacktrace:
 [1] repo_and_version_of_pull_request_body(body::Nothing)
   @ RegistryCI.TagBot ~/.julia/packages/RegistryCI/3KBMb/src/TagBot/TagBot.jl:48
```

This could be handled using a separate dispatch, but this approach seems
more in line with the rest of the codebase.

Fixes #503.